# Generated by Django 5.0.2 on 2024-03-03 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Convener',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specialisations',
            fields=[
                ('specialisation', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('urn', models.SmallIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('code', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('module_convener', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.convener')),
            ],
        ),
        migrations.CreateModel(
            name='ModuleAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.academic')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.module')),
            ],
        ),
        migrations.CreateModel(
            name='AcademicSpecialisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.academic')),
                ('specialisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.specialisations')),
            ],
        ),
        migrations.CreateModel(
            name='StudentAcademic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isModerator', models.BooleanField(default=False)),
                ('academic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.academic')),
                ('urn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentModuleMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.IntegerField()),
                ('moduleCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.module')),
                ('urn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.student')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPreferredSpecialisations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.specialisations')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fire.student')),
            ],
        ),
    ]
