# Generated by Django 5.0.2 on 2024-03-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fire', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='urn',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentmodulemark',
            name='mark',
            field=models.IntegerField(null=True),
        ),
    ]
